---

- name: create /etc/httpd/conf.d/{{project}}.conf
  template:
    src: vhost.conf.j2
    dest: /etc/httpd/conf.d/{{project}}.conf

- name: create /etc/httpd/conf.d/{{project}}-ssl.conf
  template:
    src: vhost.ssl.conf.j2
    dest: /etc/httpd/conf.d/{{project}}-ssl.conf

- name: Copy star.wiebekn.dev.crt
  copy:
    src: star.wiebekn.dev.crt
    dest: /etc/pki/tls/certs/

- name: Copy star.wiebekn.dev.key
  copy:
    src: star.wiebekn.dev.key
    dest: /etc/pki/tls/private/

- name: composer install
  composer:
    command: install
    working_dir: "{{basedir}}/{{project}}/src"
    no_dev: no

- name: create database tables.
  command: php artisan migrate
  args:
    chdir: "{{basedir}}/{{project}}/src"

- name: fill database with test data.
  command: php artisan db:seed
  args:
    chdir: "{{basedir}}/{{project}}/src"

- name: Allow httpd to access storage
  sefcontext:
    target: '{{basedir}}/{{project}}/src/(storage/.*)?'
    setype: httpd_sys_rw_content_t
    state: present

- name: Allow httpd to access bootstap/cache
  sefcontext:
    target: '{{basedir}}/{{project}}/src/bootstrap/(cache/.*)?'
    setype: httpd_sys_rw_content_t
    state: present

- name: Apply new SELinux file context to filesystem
  command: restorecon -irv {{basedir}}/{{project}}/*

- name: Install supervisor
  yum:
    name: supervisor
    state: present

- name: Copy websockets.conf
  copy:
    src: websockets.conf
    dest: /etc/supervisord.d/
  notify: restart websockets

- name: Start the websockets service
  service:
    name: supervisord
    state: started
    enabled: yes

- name: restart httpd
  service:
    name: httpd
    enabled: yes
    state: restarted
